# NOTE: This is still in progress, so if this fails it may need editing! 
name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Run ESLint
      run: npm run lint
