# NOTE: This is still in progress, so if this fails it may need editing! 
name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stefanoeb/eslint-action@1.0.2
    - name: Install modules
      run: npm install eslint --save-dev
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
